export const currencySelected = [
  { code: 'CAD', name: 'Canadian Dollar', decimal: '2', exchangeRate: 1.34},
  { code: 'EUR', name: 'Euro', decimal: '2',  exchangeRate: 0.85},
  { code: 'PLN', name: 'New Polish Zloty', decimal: '2',  exchangeRate: 3.75 },
  { code: 'USD', name: 'US Dollars', decimal: '2',   exchangeRate: 1},
];
export const currency = [
  { code: 'AED', name: 'UAE Dirham', decimal: '2' },
  { code: 'ALL', name: 'Albanian Lek', decimal: '2' },
  { code: 'AMD', name: 'Armenian Dram', decimal: '2' },
  { code: 'ANG', name: 'Antillian Guilder', decimal: '2' },
  { code: 'AOA', name: 'Angolan Kwanza', decimal: '2' },
  { code: 'ARS', name: 'Nuevo Argentine Peso', decimal: '2' },
  { code: 'AUD', name: 'Australian Dollar', decimal: '2' },
  { code: 'AWG', name: 'Aruban Guilder', decimal: '2' },
  { code: 'AZN', name: 'Azerbaijani manat', decimal: '2' },
  { code: 'BAM', name: 'Bosnia and Herzegovina Convertible Marks', decimal: '2' },
  { code: 'BBD', name: 'Barbados Dollar', decimal: '2' },
  { code: 'BDT', name: 'Bangladesh Taka', decimal: '2' },
  { code: 'BGN', name: 'New Bulgarian Lev', decimal: '2' },
  { code: 'BHD', name: 'Bahraini Dinar', decimal: '3' },
  { code: 'BMD', name: 'Bermudian Dollar', decimal: '2' },
  { code: 'BND', name: 'Brunei Dollar', decimal: '2' },
  { code: 'BOB', name: 'Bolivia Boliviano', decimal: '2' },
  { code: 'BRL', name: 'Brazilian Real', decimal: '2' },
  { code: 'BSD', name: 'Bahamian Dollar', decimal: '2' },
  { code: 'BWP', name: 'Botswana Pula', decimal: '2' },
  { code: 'BYN', name: 'New Belarusian Ruble', decimal: '2' },
  { code: 'BZD', name: 'Belize Dollar', decimal: '2' },
  { code: 'CAD', name: 'Canadian Dollar', decimal: '2' },
  { code: 'CHF', name: 'Swiss Franc', decimal: '2' },
  { code: 'CLP', name: 'Chilean Peso	2 (see not', edecimal: ')' },
  { code: 'CNY', name: 'Yuan Renminbi', decimal: '2' },
  { code: 'COP', name: 'Colombian Peso', decimal: '2' },
  { code: 'CRC', name: 'Costa Rican Colon', decimal: '2' },
  { code: 'CSD', name: 'Serbian Dinar', decimal: '2' },
  { code: 'CUP', name: 'Cuban Peso', decimal: '2' },
  { code: 'CVE', name: 'Cape Verdi Escudo	0 (see not', edecimal: ')' },
  { code: 'CZK', name: 'Czech Koruna', decimal: '2' },
  { code: 'DJF', name: 'Djibouti Franc', decimal: '0' },
  { code: 'DKK', name: 'Danish Krone', decimal: '2' },
  { code: 'DOP', name: 'Dominican Republic Peso', decimal: '2' },
  { code: 'DZD', name: 'Algerian Dinar', decimal: '2' },
  { code: 'EEK', name: 'Estonian Krone', decimal: '2' },
  { code: 'EGP', name: 'Egyptian Pound', decimal: '2' },
  { code: 'ETB', name: 'Ethiopian Birr', decimal: '2' },
  { code: 'EUR', name: 'Euro', decimal: '2' },
  { code: 'FJD', name: 'Fiji Dollar', decimal: '2' },
  { code: 'FKP', name: 'Falkland Islands Pound', decimal: '2' },
  { code: 'GBP', name: 'Pound Sterling', decimal: '2' },
  { code: 'GEL', name: 'Georgian Lari', decimal: '2' },
  { code: 'GHS', name: 'Ghanaian Cedi (3rd)', decimal: '2' },
  { code: 'GIP', name: 'Gibraltar Pound', decimal: '2' },
  { code: 'GMD', name: 'Gambia Delasi', decimal: '2' },
  { code: 'GNF', name: 'Guinea Franc', decimal: '0' },
  { code: 'GTQ', name: 'Guatemala Quetzal', decimal: '2' },
  { code: 'GYD', name: 'Guyanese Dollar', decimal: '2' },
  { code: 'HKD', name: 'Hong Kong Dollar', decimal: '2' },
  { code: 'HNL', name: 'Honduras Lempira', decimal: '2' },
  { code: 'HRK', name: 'Croatia Kuna', decimal: '2' },
  { code: 'HTG', name: 'Haitian Gourde', decimal: '2' },
  { code: 'HUF', name: 'Hungarian Forint', decimal: '2' },
  { code: 'IDR', name: 'Indonesian Rupiah	0 (see not', edecimal: ')' },
  { code: 'ILS', name: 'New Israeli Scheqel', decimal: '2' },
  { code: 'INR', name: 'Indian Rupee', decimal: '2' },
  { code: 'IQD', name: 'Iraqi Dinar', decimal: '3' },
  { code: 'ISK', name: 'Iceland Krona	2 (see not', edecimal: ')' },
  { code: 'JMD', name: 'Jamaican Dollar', decimal: '2' },
  { code: 'JOD', name: 'Jordanian Dinar', decimal: '3' },
  { code: 'JPY', name: 'Japanese Yen', decimal: '0' },
  { code: 'KES', name: 'Kenyan Shilling', decimal: '2' },
  { code: 'KGS', name: 'Kyrgyzstan Som', decimal: '2' },
  { code: 'KHR', name: 'Cambodia Riel', decimal: '2' },
  { code: 'KMF', name: 'Comoro Franc', decimal: '0' },
  { code: 'KRW', name: 'South-Korean Won', decimal: '0' },
  { code: 'KWD', name: 'Kuwaiti Dinar', decimal: '3' },
  { code: 'KYD', name: 'Cayman Islands Dollar', decimal: '2' },
  { code: 'KZT', name: 'Kazakhstani Tenge', decimal: '2' },
  { code: 'LAK', name: 'Laos Kip', decimal: '2' },
  { code: 'LBP', name: 'Lebanese Pound', decimal: '2' },
  { code: 'LKR', name: 'Sri Lanka Rupee', decimal: '2' },
  { code: 'LTL', name: 'Lithunianian Litas', decimal: '2' },
  { code: 'LVL', name: 'Latvian Lats', decimal: '2' },
  { code: 'LYD', name: 'Libyan Dinar', decimal: '3' },
  { code: 'MAD', name: 'Moroccan Dirham', decimal: '2' },
  { code: 'MDL', name: 'Moldovia Leu', decimal: '2' },
  { code: 'MKD', name: 'Macedonian Denar', decimal: '2' },
  { code: 'MMK', name: 'Myanmar Kyat', decimal: '2' },
  { code: 'MNT', name: 'Mongolia Tugrik', decimal: '2' },
  { code: 'MOP', name: 'Macau Pataca', decimal: '2' },
  { code: 'MRU', name: 'Mauritania Ouguiya', decimal: '2' },
  { code: 'MUR', name: 'Mauritius Rupee', decimal: '2' },
  { code: 'MVR', name: 'Maldives Rufiyaa', decimal: '2' },
  { code: 'MWK', name: 'Malawi Kwacha', decimal: '2' },
  { code: 'MXN', name: 'Mexican Peso', decimal: '2' },
  { code: 'MYR', name: 'Malaysian Ringgit', decimal: '2' },
  { code: 'MZN', name: 'Mozambican Metical', decimal: '2' },
  { code: 'NAD', name: 'Namibian Dollar', decimal: '2' },
  { code: 'NGN', name: 'Nigerian Naira', decimal: '2' },
  { code: 'NIO', name: 'Nicaragua Cordoba Oro', decimal: '2' },
  { code: 'NOK', name: 'Norwegian Krone', decimal: '2' },
  { code: 'NPR', name: 'Nepalese Rupee', decimal: '2' },
  { code: 'NZD', name: 'New Zealand Dollar', decimal: '2' },
  { code: 'OMR', name: 'Rial Omani', decimal: '3' },
  { code: 'PAB', name: 'Panamanian Balboa', decimal: '2' },
  { code: 'PEN', name: 'Peruvian Nuevo Sol', decimal: '2' },
  { code: 'PGK', name: 'New Guinea Kina', decimal: '2' },
  { code: 'PHP', name: 'Philippine Peso', decimal: '2' },
  { code: 'PKR', name: 'Pakistan Rupee', decimal: '2' },
  { code: 'PLN', name: 'New Polish Zloty', decimal: '2' },
  { code: 'PYG', name: 'Paraguay Guarani', decimal: '0' },
  { code: 'QAR', name: 'Qatari Rial', decimal: '2' },
  { code: 'RON', name: 'New Romanian Lei', decimal: '2' },
  { code: 'RSD', name: 'Serbian Dinar', decimal: '2' },
  { code: 'RUB', name: 'Russian Ruble', decimal: '2' },
  { code: 'RWF', name: 'Rwanda Franc', decimal: '0' },
  { code: 'SAR', name: 'Saudi Riyal', decimal: '2' },
  { code: 'SBD', name: 'Solomon Island Dollar', decimal: '2' },
  { code: 'SCR', name: 'Seychelles Rupee', decimal: '2' },
  { code: 'SEK', name: 'Swedish Krone', decimal: '2' },
  { code: 'SGD', name: 'Singapore Dollar', decimal: '2' },
  { code: 'SHP', name: 'St. Helena Pound', decimal: '2' },
  { code: 'SKK', name: 'Slovak Koruna', decimal: '2' },
  { code: 'SLL', name: 'Sierra Leone Leone', decimal: '2' },
  { code: 'SOS', name: 'Somalia Shilling', decimal: '2' },
  { code: 'SRD', name: 'Surinamese dollar', decimal: '2' },
  { code: 'STN', name: 'Sao Tome & Principe Dobra', decimal: '2' },
  { code: 'SVC', name: 'El Salvador Colón', decimal: '2' },
  { code: 'SZL', name: 'Swaziland Lilangeni', decimal: '2' },
  { code: 'THB', name: 'Thai Baht', decimal: '2' },
  { code: 'TND', name: 'Tunisian Dinar', decimal: '3' },
  { code: 'TOP', name: 'Tonga Paanga',	decimal: '2'},
  { code: 'TRY', name: 'New Turkish Lira', decimal: '2' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', decimal: '2' },
  { code: 'TWD', name: 'New Taiwan Dollar', decimal: '2' },
  { code: 'TZS', name: 'Tanzanian Shilling', decimal: '2' },
  { code: 'UAH', name: 'Ukraine Hryvnia', decimal: '2' },
  { code: 'UGX', name: 'Uganda Shilling', decimal: '0' },
  { code: 'USD', name: 'US Dollars', decimal: '2' },
  { code: 'UYU', name: 'Peso Uruguayo', decimal: '2' },
  { code: 'UZS', name: 'Uzbekistani Som', decimal: '2' },
  { code: 'VEF', name: 'Venezuelan Bolívar', decimal: '2' },
  { code: 'VND', name: 'Vietnamese New Dong', decimal: '0' },
  { code: 'VUV', name: 'Vanuatu Vatu', decimal: '0' },
  { code: 'WST', name: 'Samoan Tala', decimal: '2' },
  { code: 'XAF', name: 'CFA Franc BEAC', decimal: '0' },
  { code: 'XCD', name: 'East Carribean Dollar', decimal: '2' },
  { code: 'XOF', name: 'CFA Franc BCEAO', decimal: '0' },
  { code: 'XPF', name: 'CFP Franc', decimal: '0' },
  { code: 'YER', name: 'Yemeni Rial', decimal: '2' },
  { code: 'ZAR', name: 'South African Rand', decimal: '2' },
  { code: 'ZMW', name: 'Zambian Kwacha',	decimal: '2'},
];